version: '3.9'

services:
  postgres:
    build: ./postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - backend

  django:
    build: ./django
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - django
    networks:
      - backend
    volumes:  
      - web-data:/var/www/html

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DB_VOLUME_PATH
  web-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $WEB_VOLUME_PATH

networks:
  backend:
    driver: bridge